In [1]:
import os
import IPython.display as ipd
import audioread
import csv
import librosa
from tqdm import tqdm_notebook
import sklearn
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

home = "C:\\Users\\Amar Srinivasan\\Documents\\Music-Analysis-Project"

In [2]:
genre_dict = {}

In [3]:
os.chdir(home)
with open("genre_map.csv","r") as genre_map:
    reader = csv.reader(genre_map)
    for row in reader:
        genre_dict[row[0]] = row[1]

### Constructing the Dataset

In [4]:
headers = ["Audio Mean", "Zero Crossings", "Spectral Centroid", "Rolloff"]
for i in range(1,21):
    headers.append(f"MFCC {i}")
headers.append("Genre")

In [15]:
os.chdir(home + "\\fma_small")
folders = os.listdir()
with open("song_data.csv", 'w', newline = "") as f:
    writer = csv.writer(f)
    writer.writerow(headers)
    for f in folders:
        if f not in ['checksums', 'README']:
            os.chdir(f)
            songs = os.listdir()
            print(f)
            for song in tqdm_notebook(songs):
                try:
                    song_id = song.replace(".mp3", "").lstrip('0')
                    if song_id in genre_dict.keys():
                        song_genre = genre_dict[song_id]

                        ### FEATURE SELECTION PORTION ###
                        audio,sr = librosa.load(song)
                        audio = np.trim_zeros(audio)
                        audio_mean = audio.mean()
                        zero_crossings = sum(librosa.zero_crossings(audio, pad = False))
                        spectral_centroid = librosa.feature.spectral_centroid(audio, sr = sr).mean()              
                        mfcc = librosa.feature.mfcc(audio, sr = sr)
                        rolloff = librosa.feature.spectral_rolloff(audio, sr = sr).mean()
                        mfcc_list = [np.mean(e) for e in mfcc]

                        data_list = [audio_mean, zero_crossings, spectral_centroid, rolloff]
                        data_list += mfcc_list + [song_genre]
                        writer.writerow(data_list)
                except:
                    print(f"Error with song {song_id} in folder {f}.")
            os.chdir("..")

000



001



002



003



004



005



006



007



008



009



010



011



012



013



014



015



016



017



018



019



020



021



022



023



024



025



026



027



028



029



030



031



032



033



034



035



036



037



038



039



040



041



042



043



044



045



046



047



048



049



050



051



052



053



054



055



056



057



058



059



060



061



062



063



064



065



066



067



068



069



070



071



072



073



074



075



076



077



078



079



080



081



082



083



084



085



086



087



088



089



090



091



092



093



094



095



096



097



098



099


Error with song 99134 in folder 099.

100



101



102



103



104



105



106



107


c:\users\amar srinivasan\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:20: RuntimeWarning: Mean of empty slice.
c:\users\amar srinivasan\appdata\local\programs\python\python37\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)


Error with song 107535 in folder 107.

108


Error with song 108925 in folder 108.

109



110



111



112



113



114


NotADirectoryError: [WinError 267] The directory name is invalid: 'README.txt'

<class 'str'>


In [17]:
os.getcwd()

'C:\\Users\\Amar Srinivasan\\Documents\\Music-Analysis-Project\\fma_small'

In [18]:
songs = pd.read_csv("song_data.csv")
songs.shape

(5337, 25)

In [5]:
with open("test.csv", "w") as f:
    writer = csv.writer(f)
    writer.writerow(["This, is, a, test"])

In [12]:
'''
import matplotlib.pyplot as plt
import librosa.display


plt.figure(figsize=(14, 5))
librosa.display.waveplot(test_song[1:15000], sr=sr)
plt.show()
'''

'\nimport matplotlib.pyplot as plt\nimport librosa.display\n\n\nplt.figure(figsize=(14, 5))\nlibrosa.display.waveplot(test_song[1:15000], sr=sr)\nplt.show()\n'

### Creating a Machine Learning Model using SVM Classifiers

In [19]:
X = songs.drop('Genre', axis = 1)
y = songs['Genre']

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [ ]:
# Implementing gridsearchCV
from sklearn.model_selection import GridSearchCV

grid_param = {'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001], 'kernel': ['rbf', 'poly', 'sigmoid']}
grid = GridSearchCV(SVC(), grid_param, refit = True, verbose = 2, njobs = -1)
grid.fit(X_train, y_train)

c:\users\amar srinivasan\appdata\local\programs\python\python37\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Fitting 3 folds for each of 48 candidates, totalling 144 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] ....................... C=0.1, gamma=1, kernel=rbf, total=   1.9s


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.8s remaining:    0.0s


[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] ....................... C=0.1, gamma=1, kernel=rbf, total=   2.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] ....................... C=0.1, gamma=1, kernel=rbf, total=   1.9s
[CV] C=0.1, gamma=1, kernel=poly .....................................


In [21]:
from sklearn.metrics import classification_report, confusion_matrix

kernels = ['Linear', 'RBF', 'Sigmoid', "Polynomial"]
for k in kernels:
    print(f"Testing SVM with {k} kernel")
    svclassifier = SVC(kernel='linear')
    svclassifier.fit(X_train, y_train)
    y_pred = svclassifier.predict(X_test)
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))

[[51 19  4 42  4  6  3  7]
 [23 54 20 12  8 21  6 15]
 [ 5 16 76  1  4 16  5 13]
 [26 11  3 81  2 12  5 11]
 [ 8 13 12  2 12  9  2 11]
 [15 19  6 13  0 64 10 12]
 [30 18  6 15  4 23 13 28]
 [ 9  6  5 11  3  6  5 96]]
               precision    recall  f1-score   support

   Electronic       0.31      0.38      0.34       136
 Experimental       0.35      0.34      0.34       159
         Folk       0.58      0.56      0.57       136
      Hip-Hop       0.46      0.54      0.49       151
 Instrumental       0.32      0.17      0.23        69
International       0.41      0.46      0.43       139
          Pop       0.27      0.09      0.14       137
         Rock       0.50      0.68      0.57       141

     accuracy                           0.42      1068
    macro avg       0.40      0.40      0.39      1068
 weighted avg       0.40      0.42      0.40      1068



               precision    recall  f1-score   support

   Electronic       0.34      0.31      0.33       113
 Experimental       0.20      0.21      0.20       134
         Folk       0.47      0.42      0.45       125
      Hip-Hop       0.32      0.55      0.40       110
 Instrumental       0.15      0.14      0.14        37
International       0.39      0.49      0.44       150
          Pop       0.11      0.02      0.03       117
         Rock       0.26      0.25      0.26       106

     accuracy                           0.32       892
    macro avg       0.28      0.30      0.28       892
 weighted avg       0.30      0.32      0.30       892



Audio  Zero Crossing Rate  Spectral Centroid       MFCC  \
2      3.134626e-04              108341        3037.939465  -0.633934   
5      6.858170e-05               66268        2413.923644   2.423232   
10     2.394305e-05               98403        2349.568550   2.009282   
140    9.984850e-06               29326        1748.028062  -3.714334   
141    9.728277e-07               40947        1655.168568  -3.491436   
148   -7.504798e-03               59699        1707.284495  11.613784   
182    3.628743e-06               66618        1876.689601   7.559654   
190    1.196952e-06               58530        1899.980137  -9.224703   
193    4.717180e-05               51105        1583.172605 -10.606495   
194   -1.801641e-05               48273        1546.720808  -9.238567   
197   -1.468754e-05               35792        1142.980123 -13.552857   
200   -9.431456e-06               64600        1918.444563  -7.221779   
203    1.943993e-05               34750        1347.367914 -13.271733   
204   -1.968748e-04               53335        1765.997137  -6.274412   
207   -1.166088e-05               40449        1244.830166 -17.663004   
210   -4.837467e-05               56314        1822.833650  -6.479299   
211    5.099610e-06               52048        1594.354456  -8.022534   
212    8.225244e-04               69893        2331.548811   1.556785   
213    1.138028e-05               35749        1131.880907  -8.438511   
255    4.293929e-06               39844        1255.908029  -1.674967   
256    3.122093e-03               76558        2193.704022   7.184227   
368    2.909876e-06               30836        1518.285951  -1.116032   
424   -3.867409e-07               79655        1853.162537  -6.075626   
459    5.402260e-05               42076        1947.668600   9.452703   
534    2.870615e-06               26901        1010.592244  -3.152024   
540   -2.938213e-07               40506        1385.433490  -3.682946   
546   -8.697170e-06               37526        1264.101081  -3.632506   
574   -2.099858e-04               95021        2609.777655   4.184554   
602    1.056275e-06               22935         766.771247 -13.367497   
615   -6.450604e-06               12547         396.869016  -7.864735   
...             ...                 ...                ...        ...   
98617 -1.870879e-03               71818        2563.473564   6.699312   
98618  5.111492e-04               58575        2337.282464   0.515490   
98619 -8.284388e-04               67704        2304.704554   5.901703   
98620  1.251275e-05               70945        2500.376432   5.317148   
98621  1.036239e-05               56557        1815.634385  -3.953747   
98622  7.516735e-04               66686        2747.295071   9.028548   
98623 -3.148588e-04               47296        2105.686227   9.395184   
98624 -7.203522e-04               65680        2275.675545   6.446916   
98625 -4.990325e-04               67021        2318.719117   6.728050   
98626 -3.163881e-05               50029        2296.976940   7.826365   
98627 -9.977705e-04               61981        2268.637873   6.670063   
98628 -4.473124e-05               51942        2199.908038   9.360744   
98655 -3.611138e-05               80763        2442.142303 -16.670162   
98656 -3.547579e-05               86270        2549.861011 -15.455774   
98657 -3.633813e-05              111744        2719.629290 -17.054348   
98666 -3.943724e-05               63804        1927.924310  -8.458186   
98667  5.051187e-04               79245        2653.639636   6.056706   
98668  1.783015e-04               57152        2097.941220   2.879441   
98669 -7.029617e-05               69306        2374.532105   2.244050   
98670  2.060263e-05               91125        2675.264914   0.968652   
98671  5.665856e-06               75865        2528.612620   2.337654   
98680 -2.504732e-05              128141        2713.188902 -14.992867   
98681 -1.053807e-05              121296        2708.869665  -9.094324   

In [ ]:
# Plays a song
os.startfile(songs[0])
ipd.Audio(songs[0])

<class 'numpy.ndarray'>
<class 'numpy.int32'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'str'>
